name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup
        run: |
          brew install llvm@18 bison re2c

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --target x_test -j $(nproc)

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure
